In [8]:
import numpy as np
import pandas as pd
from pandas import Series,DataFrame
import matplotlib.pyplot as plt
%matplotlib inline
import math
import seaborn as sns

from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

from sklearn import metrics

import statsmodels.api as sm

ModuleNotFoundError: No module named 'statsmodels'

In [ ]:
def logistic(t):
    return 1.0/(1+math.exp(-1*t))
t=np.linspace(6,-6,500)
y=np.array([logistic(element) for element in t])
plt.plot(t,y)
plt.title("logistic function")

In [6]:
df=sm.datasets.fair.load_pandas().data
#http://www.statsmodels.org/stable/datasets/generated/fair.html
df.head()

NameError: name 'sm' is not defined

In [ ]:
def affair_check(x):
    if x!=0:
        return 1
    else:
        return 0
df["Had_Affair"]=df['affairs'].apply(affair_check)
df.head()

In [ ]:
age_group=df.drop(['rate_marriage','yrs_married','children','religious','educ','occupation','occupation_husb'],axis=1)
age_group.head()
#this could also be done using 
# age_group=pd.concat([df['age'],df['affairs'],df['Had_Affair']],axis=1)

In [ ]:
age_group=pd.concat([df['age'],df['affairs'],df['Had_Affair']],axis=1)

In [ ]:
age_group_frame=age_group.groupby(['age','Had_Affair']).count()
age_group_frame

In [ ]:
age=[]
for i in range(0,len(age_group_frame['affairs'])):
    age.append(age_group_frame.index[i][0])
age


In [ ]:
affair_not=[]
affair=[]
for i in range(0,len(age_group_frame['affairs'])):
    if age_group_frame.index[i][1]==0:
        affair_not.append(age_group_frame['affairs'][i])
        affair.append(0)
    if age_group_frame.index[i][1]==1:
        affair.append(age_group_frame['affairs'][i])
        affair_not.append(0)

In [ ]:
affair_not

In [ ]:
affair

In [ ]:
plt.bar(age,affair_not,width=-2.0,align='edge')
plt.bar(age,affair,width=2.0,align='edge')
plt.title("Age vs Affair Count")
plt.xlabel("age")
plt.ylabel("counts")
#plt.legend((affair_not,affair),('Not Affair','Affair'),loc='lower left')
plt.show()

In [ ]:
sns.countplot('age',data=df,hue='Had_Affair',palette='coolwarm')

In [2]:
sns.countplot('educ',data=df,hue='Had_Affair')

NameError: name 'df' is not defined

In [3]:
sns.countplot('yrs_married',data=df,hue='Had_Affair')

NameError: name 'df' is not defined

In [4]:
sns.countplot('children',data=df,hue='Had_Affair',palette='coolwarm')

NameError: name 'df' is not defined

In [5]:
occ_dummies=pd.get_dummies(df['occupation'])
hus_occ_dummies=pd.get_dummies(df['occupation_husb'])
occ_dummies.head() 

NameError: name 'df' is not defined

In [44]:
hus_occ_dummies.head()

1.0  2.0  3.0  4.0  5.0  6.0
0    0    0    0    0    1    0
1    0    0    0    1    0    0
2    0    0    0    0    1    0
3    0    0    0    0    1    0
4    0    0    0    1    0    0

In [53]:
occ_dummies.columns=['occ1','occ2','occ3','occ4','occ5','occ6']
hus_occ_dummies.columns=['hocc1','hocc2','hocc3','hocc4','hocc5','hocc6']
X=df.drop(['occupation','occupation_husb','Had_Affair'],axis=1)
X=pd.concat([X,occ_dummies],axis=1)
X=pd.concat([X,hus_occ_dummies],axis=1)
X.head()

rate_marriage   age  yrs_married  children  religious  educ   affairs  \
0            3.0  32.0          9.0       3.0        3.0  17.0  0.111111   
1            3.0  27.0         13.0       3.0        1.0  14.0  3.230769   
2            4.0  22.0          2.5       0.0        1.0  16.0  1.400000   
3            4.0  37.0         16.5       4.0        3.0  16.0  0.727273   
4            5.0  27.0          9.0       1.0        1.0  14.0  4.666666   

   had_affair  occ1  occ2  occ3  occ4  occ5  occ6  hocc1  hocc2  hocc3  hocc4  \
0           1     0     1     0     0     0     0      0      0      0      0   
1           1     0     0     1     0     0     0      0      0      0      1   
2           1     0     0     1     0     0     0      0      0      0      0   
3           1     0     0     0     0     1     0      0      0      0      0   
4           1     0     0     1     0     0     0      0      0      0      1   

   hocc5  hocc6  
0      1      0  
1      0      0  
2      1      0  
3      1      0  
4      0      0

In [54]:
Y=df.Had_Affair
Y.tail()

6361    0
6362    0
6363    0
6364    0
6365    0
Name: Had_Affair, dtype: int64

In [55]:
X = X.drop(['affairs','had_affair'],axis=1)
X.head()

rate_marriage   age  yrs_married  children  religious  educ  occ1  occ2  \
0            3.0  32.0          9.0       3.0        3.0  17.0     0     1   
1            3.0  27.0         13.0       3.0        1.0  14.0     0     0   
2            4.0  22.0          2.5       0.0        1.0  16.0     0     0   
3            4.0  37.0         16.5       4.0        3.0  16.0     0     0   
4            5.0  27.0          9.0       1.0        1.0  14.0     0     0   

   occ3  occ4  occ5  occ6  hocc1  hocc2  hocc3  hocc4  hocc5  hocc6  
0     0     0     0     0      0      0      0      0      1      0  
1     1     0     0     0      0      0      0      1      0      0  
2     1     0     0     0      0      0      0      0      1      0  
3     0     0     1     0      0      0      0      0      1      0  
4     1     0     0     0      0      0      0      1      0      0

In [56]:
Y=np.ravel(Y)
Y

array([1, 1, 1, ..., 0, 0, 0], dtype=int64)

In [59]:
log_model=LogisticRegression()

log_model.fit(X,Y)

log_model.score(X,Y)

c:\users\hp\appdata\local\programs\python\python36-32\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


0.7260446120012567

In [60]:
log_model

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [61]:
Y.mean()

0.3224945020420987

In [63]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y)
print(X_train.shape,X_test.shape,Y_train.shape,Y_test.shape)

(4774, 18) (1592, 18) (4774,) (1592,)


In [65]:
log_model2=LogisticRegression()
log_model2.fit(X_train,Y_train)
log_model2.score(X_train,Y_train)

c:\users\hp\appdata\local\programs\python\python36-32\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


0.7276916631755341

In [66]:
log_model3=LogisticRegression()
log_model.fit(X_test,Y_test)
log_model.score(X_test,Y_test)

c:\users\hp\appdata\local\programs\python\python36-32\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


0.7160804020100503

In [68]:
class_predict=log_model2.predict(X_test)
class_predict

array([1, 0, 0, ..., 0, 0, 0], dtype=int64)

In [73]:
metrics.accuracy_score(Y_test,class_predict)

0.7261306532663316

In [75]:
Y_train

array([0, 1, 1, ..., 0, 0, 0], dtype=int64)

In [76]:
Y_test

array([1, 0, 0, ..., 0, 0, 1], dtype=int64)

In [77]:
X_train.head()

rate_marriage   age  yrs_married  children  religious  educ  occ1  occ2  \
3775            3.0  32.0          6.0       0.0        2.0  14.0     0     0   
101             5.0  37.0         16.5       4.0        1.0  12.0     0     0   
2045            4.0  32.0         13.0       3.0        1.0  20.0     0     0   
6312            5.0  22.0          2.5       1.0        4.0  16.0     0     0   
6122            4.0  27.0          6.0       2.0        1.0  14.0     0     0   

      occ3  occ4  occ5  occ6  hocc1  hocc2  hocc3  hocc4  hocc5  hocc6  
3775     1     0     0     0      0      0      0      0      1      0  
101      1     0     0     0      0      0      0      0      0      1  
2045     0     0     1     0      0      0      0      0      1      0  
6312     0     1     0     0      0      0      0      0      1      0  
6122     0     0     1     0      0      0      0      0      1      0

In [78]:
X_test.head()

rate_marriage   age  yrs_married  children  religious  educ  occ1  occ2  \
987             3.0  42.0         23.0       3.0        2.0  14.0     0     0   
3910            4.0  42.0         23.0       4.0        4.0  14.0     1     0   
6175            4.0  27.0          2.5       1.0        3.0  14.0     0     0   
3723            4.0  27.0          6.0       1.0        4.0  16.0     0     0   
4122            5.0  22.0          0.5       0.0        2.0  12.0     0     0   

      occ3  occ4  occ5  occ6  hocc1  hocc2  hocc3  hocc4  hocc5  hocc6  
987      0     0     1     0      0      0      0      1      0      0  
3910     0     0     0     0      0      0      0      0      1      0  
6175     0     1     0     0      0      1      0      0      0      0  
3723     0     1     0     0      0      0      0      1      0      0  
4122     0     1     0     0      0      0      0      1      0      0

In [10]:
from gTTs import gtts

ModuleNotFoundError: No module named 'gTTs'