In [1]:
import numpy as np
l=np.array([1,2,3,4,5])
l1=np.array([6,7,8,9,10])
print(l+l1)
l2=l-l1
print(l2)
print(l*l1)
print(l/l1)

[ 7  9 11 13 15]
[-5 -5 -5 -5 -5]
[ 6 14 24 36 50]
[0.16666667 0.28571429 0.375      0.44444444 0.5       ]


In [3]:
##bs4
from bs4 import BeautifulSoup
import requests
url="https://grras.com"
data=requests.get(url)
summary=data.content
soup=BeautifulSoup(summary)
print(soup.prettify)
para=soup.find('div',{'class':'program_box'})
print(para)
para.find_all('p')

<bound method Tag.prettify of <!DOCTYPE doctype html>

<html class="no-js" lang="">
<head>
<meta charset="utf-8"/>
<meta content="ie=edge" http-equiv="x-ua-compatible"/>
<title>Grras Solutions – AWS-Cloud, CCNA &amp; RedHat Linux Certification &amp; Training</title>
<meta content="CCNA training in Jaipur, CCNA training in Ahmedabad, RedHat Certification in Jaipur, RedHat Certification in Indore, RedHat Certification in Ahmedabad, AWS Cloud Certification in Jaipur, AWS Cloud Certification in Indore, AWS Cloud Certification in Ahmedabad" name="keywords"/>
<meta content="Grras Solutions is one of the best CCNA, Red Hat Linux ( RHCSA &amp; RHCE ) and AWS cloud Certification and training provider in Jaipur, Ahmedabad and Indore." name="description"/>
<link href="https://grras.com/" rel="canonical"/>
<meta content="Linux Training Institute, RedHat Training Center" name="classification"/>
<meta content="Linux Training Institute, RedHat Training Center" name="copyright">
<meta content="GRRAS S

[<p>One can select the technology they want to study or group different technologies they want to learn. Enroll with us to get hands-on-lab experience in RedHat, AWS, Python, Artificial Intelligence, Cloud Computing, DevOps, Bigdata, and CISCO with us. </p>]

In [4]:
from bs4 import BeautifulSoup
import requests
url='http://www.ucop.edu/operating-budget/budgets-and-reports/legislative-reports/2013-14-legislative-session.html/'
result=requests.get(url)
c=result.content
soup=BeautifulSoup(c)
print(soup.prettify)

<bound method Tag.prettify of 
<!DOCTYPE html>

<!--[if lt IE 9]><html class="lte-ie8 no-js"  lang="en"><![endif]-->
<!--[if gt IE 8]><!--><html class="no-js" lang="en"><!--<![endif]-->
<html lang="en" xml:lang="en" xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta content="IE=edge" http-equiv="X-UA-Compatible"/>
<meta charset="utf-8"/>
<meta content="width=device-width, initial-scale=1.0" name="viewport"/>
<meta content="" name="description"/>
<meta content="" name="author"/>
<title>File not found | UCOP</title>
<!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
<!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
<!-- Le styles -->
<!-- main.css - see /_common/files/css/main.less non-minified sources -->
<link href="/_common/files/css/main.css?v=1.1" media="screen" rel="stylesheet"/>
<link href="/_common/files/css/print.css" media="print" rel="stylesheet"/>
<!-- Le fav and touch icons
<link href="/files/img/ico/f

In [5]:
summary=soup.find('div',{'class':'list_land','id':'content'})
print(summary)

None


In [6]:
table=summary.find_all('table')
print(table)

AttributeError: 'NoneType' object has no attribute 'find_all'

In [ ]:
rows=table[0].find_all('tr')
data=[]
for tr in rows:
    col=tr.find_all('td')
    for td in col:
        text=td.find(text=True)
        print(text)
        data.append(text)        

In [ ]:
reports=[]
date=[]
index=0
for line in data:
    if 'pdf' in line:
        date.append(data[index-1])
        reporst.append(line.replace(u'\xa0',u' '))
    index+=1

In [3]:
##
import numpy as np
l=[1,2,3,4,5]       #one method
l=np.array(l)
print(l.shape)
print(l.ndim)
print(l.size)
print(l.itemsize)

l=np.array([1,2,3,4,5]) #second method

(5,)
1
5
4


In [4]:
##2D array - collection of 1D array
import numpy as np
l=[1,2,3,4]
l1=[5,6,7,8,9]
l2=[1,4,5,3]
d2=np.array([l,l1,l2])
print(d2.shape)
print(d2.ndim)
print(d2.size)
print(d2.itemsize)

(3,)
1
3
4


In [6]:
import numpy as np
l=np.arange(9)      ##arange works as range() for array
print(l)

[0 1 2 3 4 5 6 7 8]


In [8]:
#to convert 1d into 2d
import numpy as np
l=np.arange(9).reshape(3,3)  #3,3 are the dimension for row and column
print(l)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [9]:
import numpy as np
l=np.arange(25).reshape(5,5)  #5,5 or 1,25 or 25,1
print(l)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [10]:
import numpy as np
##1d into 3d
l1=np.arange(100).reshape(4,5,5)    ##rows = 2nd ele  ,  col=3rd ele
print(l1)                                    ##combination of rows and columns be given at the first position
                                    ##..here that value for rows is 4 

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]
  [20 21 22 23 24]]

 [[25 26 27 28 29]
  [30 31 32 33 34]
  [35 36 37 38 39]
  [40 41 42 43 44]
  [45 46 47 48 49]]

 [[50 51 52 53 54]
  [55 56 57 58 59]
  [60 61 62 63 64]
  [65 66 67 68 69]
  [70 71 72 73 74]]

 [[75 76 77 78 79]
  [80 81 82 83 84]
  [85 86 87 88 89]
  [90 91 92 93 94]
  [95 96 97 98 99]]]


In [14]:
import numpy as np
l=np.array([1,2,3,4,5])
l1=np.array([3,4,5,6,7])
print((l2=(l+l1)))
print((l3=(l-l1)))
print((l4=(l*l1)))
print((l5=(l/l1)))

#matrix multiplication
l6=l.l1
print(l6)

SyntaxError: invalid syntax (<ipython-input-14-222a49e1277a>, line 4)

In [15]:
##to make user defined arrays
import numpy as np
zero=np.zeros(4)           ##would return float type zeroes 
#we could assign the type by self 
zero=np.zeros(4,dtype=int)         ##these r for 0 and 1 only

ones=np.ones(20,dtype=int).reshape(4,5)

eye=np.eye(5)                            ##would give identity matrix
emp=np.empty(5)

In [16]:
##slicing in arrays 
import numpy as np
l=np.array([1,2,3,4])
l1=np.array([3,4,5,6])
l2=np.array([4,5,6,7])
a=np.array([l,l1,l2])
l1[1:2:1]              ##slicing is same as *list* in 1d array
                       ##for slicing in 2d array ... keep in mind that elements internally are stored in 1d form 
                       ##1st element in slicing of 2d array denotes the row value
print(a[0,0])           ## 1 would b d output 
print(a([1:3],[1:3]))
print(a([0:2],[2,4]))
print(a([0,0],[0,2],[1,0],[1,2],[2,0],[2,2]))
print(a([0:3],[0:3:+2]))

SyntaxError: invalid syntax (<ipython-input-16-7a5ba55fdb3b>, line 11)

In [17]:
#3d array
import numpy as np
a=np.array(100).reshape(5,4,5)
##**********************************

ValueError: cannot reshape array of size 1 into shape (5,4,5)